import pandas as pd
import numpy as np
import streamlit as st

# Load data
data = pd.read_csv('gold_prices.csv', index_col='Date', parse_dates=True)

# Fill missing values (if any)
data.fillna(method='ffill', inplace=True)

# Create features - For simplicity, we'll use the previous day's closing price as a feature
data['Prev_Close'] = data['Close'].shift(1)

# Drop NaN values generated by shifting
data.dropna(inplace=True)

# Add more features if needed (e.g., moving averages, RSI, etc.)
# Example: 7-day moving average
data['MA7'] = data['Close'].rolling(window=7).mean()

# Target variable: Predict whether the price will go up (1) or down (0)
data['Target'] = np.where(data['Close'].shift(-1) > data['Close'], 1, 0)

# Streamlit App
st.title('Gold Prices Analysis and Prediction')

# Display a sample of the data in a table format
st.subheader('Data Sample')
st.dataframe(data.head())  # Displays the first few rows of the DataFrame

# You can also display the entire table if needed
st.subheader('Full Data')
st.dataframe(data)  # This will show the entire DataFrame

# Alternatively, you can use st.table for a more static table view
st.table(data.head())

# Continue with any additional visualizations or analyses as needed
